set(ANDROID_ABI armeabi-v7a CACHE STRING "")

set(ANDROID_ARM_MODE NO CACHE BOOL "")
set(ANDROID_ARM_NEON YES CACHE BOOL "")
set(CMAKE_ANDROID_ARM_MODE NO CACHE BOOL "")
set(CMAKE_ANDROID_ARM_NEON YES CACHE BOOL "")
