# This is for the legacy build system
# set(CMAKE_SYSTEM_NAME "Android" CACHE STRING "")
# set(CMAKE_SYSTEM_VERSION "21" CACHE STRING "")

# set(CMAKE_ANDROID_API "21" CACHE STRING "")
# set(CMAKE_ANDROID_ARCH_ABI "x86_64" CACHE STRING "")

# set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION "clang" CACHE STRING "")
# set(CMAKE_ANDROID_STL_TYPE "c++_static" CACHE STRING "")

# New build system
set(ANDROID_ABI "x86_64" CACHE STRING "")

set(ANDROID_TOOLCHAIN clang CACHE STRING "")
set(ANDROID_PLATFORM_LEVEL 21 CACHE STRING "")
set(ANDROID_STL c++_static CACHE STRING "")
