
set(SWIFT_HOST_VARIANT_SDK ANDROID CACHE STRING "")
set(SWIFT_HOST_VARIANT_ARCH aarch64 CACHE STRING "")

# build just the standard library
set(SWIFT_INCLUDE_TOOLS NO CACHE BOOL "")
set(SWIFT_INCLUDE_TESTS NO CACHE BOOL "")
set(SWIFT_INCLUDE_DOCS NO CACHE BOOL "")

# build with the host compiler
set(SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER YES CACHE BOOL "")

message(FATAL_ERROR "${ANDROID_NDK}")

# android configuration
set(SWIFT_ANDROID_API_LEVEL "${ANDROID_PLATFORM_LEVEL}" CACHE STRING "")
set(SWIFT_ANDROID_NDK_PATH "${ANDROID_NDK}" CACHE STRING "")
set(SWIFT_ANDROID_NDK_GCC_VERSION 4.9 CACHE STRING "")
