name: curl
variables:
  platform: android
  curl.version: development
  curl.release: master
  install.directory: $(Build.StagingDirectory)/Library/libcurl-$(curl.version)
jobs:
  - job: android_armv7
    variables:
      arch: armv7
      host: arm
    steps:
      - template: templates/curl.yml

  - job: android_aarch64
    variables:
      arch: aarch64
      host: arm64
    steps:
      - template: templates/curl.yml

  - job: android_x64
    variables:
      arch: x86_64
      host: x64
    steps:
      - template: templates/curl.yml

  - job: linux_x64
    variables:
      arch: x86_64
      host: x64
      platform: linux
    steps:
    - template: templates/curl.yml
