name: curl
jobs:
  - job: android_armv7
    variables:
      arch: armv7
      host: arm
      platform: android
      curl.version: development
      install.directory: $(Build.StagingDirectory)/Library/libcurl-$(curl.version)
      curl.release: master
    steps:
      - template: templates/curl.yml

  - job: android_aarch64
    variables:
      arch: aarch64
      host: arm64
      platform: android
      curl.version: development
      install.directory: $(Build.StagingDirectory)/Library/libcurl-$(curl.version)
      curl.release: master
    steps:
      - template: templates/curl.yml

  - job: android_x64
    variables:
      arch: x86_64
      host: x64
      platform: android
      curl.version: development
      install.directory: $(Build.StagingDirectory)/Library/libcurl-$(curl.version)
      curl.release: master
    steps:
      - template: templates/curl.yml

  - job: linux_x64
    variables:
      arch: x86_64
      host: x64
      platform: linux
      curl.version: development
      install.directory: $(Build.StagingDirectory)/Library/libcurl-$(curl.version)
      curl.release: master
    steps:
    - template: templates/curl.yml
