name: icu
jobs:
  - job: android_armv7
    variables:
      arch: armv7
      host: arm
      platform: android

      icu.version: 64
      install.directory: $(Build.StagingDirectory)/Library/icu-$(icu.version)
      icu.release: maint/maint-$(icu.version)
      icu.build_tools: false
    steps:
      - template: templates/icu.yml

  - job: android_aarch64
    variables:
      arch: aarch64
      host: arm64
      platform: android

      icu.version: 64
      install.directory: $(Build.StagingDirectory)/Library/icu-$(icu.version)
      icu.release: maint/maint-$(icu.version)
      icu.build_tools: false
    steps:
      - template: templates/icu.yml

  - job: android_x64
    variables:
      arch: x86_64
      host: x64
      platform: android

      icu.version: 64
      install.directory: $(Build.StagingDirectory)/Library/icu-$(icu.version)
      icu.release: maint/maint-$(icu.version)
      icu.build_tools: false
    steps:
      - template: templates/icu.yml

  - job: linux_x64
    variables:
      arch: x86_64
      host: x64
      platform: linux

      icu.version: 64
      install.directory: $(Build.StagingDirectory)/Library/icu-$(icu.version)
      icu.release: maint/maint-$(icu.version)
      icu.build_tools: true
    steps:
      - template: templates/icu.yml
