name: libxml2
jobs:
  - job: android_armv7
    variables:
      arch: armv7
      host: arm
      platform: android
      xml2.version: development
      install.directory: $(Build.StagingDirectory)/Library/libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
      - template: templates/libxml2.yml

  - job: android_aarch64
    variables:
      arch: aarch64
      host: arm64
      platform: android
      xml2.version: development
      install.directory: $(Build.StagingDirectory)/Library/libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
      - template: templates/libxml2.yml

  - job: android_x64
    variables:
      arch: x86_64
      host: x64
      platform: android
      xml2.version: development
      install.directory: $(Build.StagingDirectory)/Library/libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
      - template: templates/libxml2.yml

  - job: linux_x64
    variables:
      arch: x86_64
      host: x64
      platform: linux
      xml2.version: development
      install.directory: $(Build.StagingDirectory)/Library/libxml2-$(XML2.Version)
      xml2.release: cmake
    steps:
    - template: templates/libxml2.yml
