name: sqlite
variables:
  sqlite.version: 3.28.0
  sqlite.release: 3280000
  platform: android
  install.directory: $(Build.StagingDirectory)/Library/sqlite-$(sqlite.version)
jobs:
  - job: android_armv7
    variables:
      arch: armv7
      host: arm
    steps:
      - template: templates/sqlite3.yml

  - job: android_aarch64
    variables:
      arch: aarch64
      host: arm64
    steps:
      - template: templates/sqlite3.yml

  - job: android_x64
    variables:
      arch: x86_64
      host: x64
    steps:
      - template: templates/sqlite3.yml

  - job: linux_x64
    variables:
      arch: x86_64
      host: x64
      platform: linux
    steps:
      - template: templates/sqlite3.yml
