name: sqlite
variables:
  sqlite.version: 3.28.0
  sqlite.release: 3280000
jobs:
  - job: android_armv7
    variables:
      arch: armv7
      host: arm
      platform: android
      install.directory: $(Build.StagingDirectory)/Library/sqlite-$(sqlite.version)
    steps:
      - template: templates/sqlite3.yml

  - job: android_aarch64
    variables:
      arch: aarch64
      host: arm64
      platform: android
      install.directory: $(Build.StagingDirectory)/Library/sqlite-$(sqlite.version)
    steps:
      - template: templates/sqlite3.yml

  - job: android_x64
    variables:
      arch: x86_64
      host: x64
      platform: android
      install.directory: $(Build.StagingDirectory)/Library/sqlite-$(sqlite.version)
    steps:
      - template: templates/sqlite3.yml
